name: Compilar EXE con Nuitka

on:
  push:
    branches: [ "main" ]

# Conceder permisos explícitos de escritura a los Releases
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install nuitka

    - name: Preparar script de entrada
      run: |
        copy src\pruebaspy\__init__.py main.py

    - name: Generar ejecutable con Nuitka
      run: |
        python -m nuitka --standalone --onefile --windows-console-mode=force --assume-yes-for-downloads --output-filename=map_dmc.exe main.py

    - name: Actualizar Release Automático
      uses: softprops/action-gh-release@v2 # Actualizado a v2 para soporte con Node moderno
      with:
        files: map_dmc.exe
        tag_name: latest
        name: Versión de Desarrollo
        body: "Actualizado automáticamente con cada cambio en el código."
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}