name: Compilar EXE con Nuitka

on:
  push:
    tags:
      - 'v*' # Se activa automáticamente cuando subes una etiqueta como v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Instalar uv y Nuitka
      run: |
        python -m pip install --upgrade pip
        pip install nuitka uv

    - name: Preparar script de entrada
      run: |
        copy src\pruebaspy\__init__.py main.py

    - name: Generar ejecutable con Nuitka
      run: |
        python -m nuitka --standalone --onefile --windows-console-mode=force --assume-yes-for-downloads --output-filename=map_dmc.exe main.py

    - name: Crear Release y Subir Ejecutable
      uses: softprops/action-gh-release@v1
      with:
        files: map_dmc.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}